import unittest

from solid2 import cube, cylinder, scad_render, sphere, translate


class ModuleTest(unittest.TestCase):
    def setUp(self):
        """Reset module registry before each test"""
        from solid2.extensions.module import _reset_module_registry

        _reset_module_registry()

    def test_module_with_custom_name(self):
        """Test creating a module with a custom name"""
        from solid2 import module

        # Create a module with custom name
        my_shape = module(cube(5) + sphere(3).translate([5, 0, 0]), name="my_shape")

        # Use the module twice
        scene = my_shape() + my_shape().translate([20, 0, 0])

        scad_output = scad_render(scene)

        # Module definition should be at the top
        self.assertIn("module my_shape()", scad_output)
        self.assertIn("cube(size = 5)", scad_output)
        self.assertIn("sphere(r = 3)", scad_output)

        # Module should be instantiated twice
        self.assertEqual(scad_output.count("my_shape();"), 2)

    def test_module_with_automatic_name(self):
        """Test creating a module with automatically generated name"""
        from solid2 import module

        # Create a module without specifying name
        my_shape = module(cube(5) + sphere(3))

        # Use the module
        scene = my_shape()

        scad_output = scad_render(scene)

        # Module definition should exist with generated name
        self.assertIn("module mod_", scad_output)
        self.assertIn("cube(size = 5)", scad_output)
        self.assertIn("sphere(r = 3)", scad_output)

    def test_module_name_stability(self):
        """Test that module names are stable and based on content"""
        from solid2 import module

        # Create a module and verify name is consistent
        shape1 = cube(5) + sphere(3)
        mod1 = module(shape1)
        first_name = mod1._module_name

        # Create the same content again (should reuse same name)
        shape2 = cube(5) + sphere(3)
        mod2 = module(shape2)

        # They should have the same generated name (stable hash)
        self.assertEqual(first_name, mod2._module_name)

        # Different content should have different names
        mod3 = module(cylinder(r=2, h=5))
        self.assertNotEqual(first_name, mod3._module_name)

    def test_module_definitions_rendered_once(self):
        """Test that module definitions are only rendered once even if used multiple times"""
        from solid2 import module

        my_shape = module(cube(5), name="test_shape")

        # Use module multiple times
        scene = my_shape() + my_shape() + my_shape()

        scad_output = scad_render(scene)

        # Module definition should appear only once
        self.assertEqual(scad_output.count("module test_shape()"), 1)

        # But instantiation should appear three times
        self.assertEqual(scad_output.count("test_shape();"), 3)

    def test_module_with_custom_prefix(self):
        """Test creating a module with custom name prefix"""
        from solid2 import module

        # Create a module with custom prefix
        my_shape = module(cube(5) + sphere(3), name_prefix="gear")

        scad_output = scad_render(my_shape())

        # Module definition should use custom prefix
        self.assertIn("module gear_", scad_output)
        self.assertNotIn("module mod_", scad_output)

        # Verify the hash part is still there
        lines = scad_output.split("\n")
        module_line = [l for l in lines if l.startswith("module gear_")][0]
        # Should be like "module gear_a3f2c1b8() {"
        self.assertTrue(module_line.startswith("module gear_"))
        self.assertIn("()", module_line)

    def test_module_default_prefix(self):
        """Test that default prefix is 'mod_' when not specified"""
        from solid2 import module

        my_shape = module(cube(5))

        scad_output = scad_render(my_shape())

        # Should use default "mod_" prefix
        self.assertIn("module mod_", scad_output)

    def test_module_duplicate_name_raises_exception(self):
        """Test that creating modules with duplicate names raises an exception"""
        from solid2 import module

        # Create first module with a name
        mod1 = module(cube(5), name="duplicate_name")

        # Trying to create another module with the same name should raise
        with self.assertRaises(ValueError) as context:
            mod2 = module(sphere(3), name="duplicate_name")

        self.assertIn("duplicate_name", str(context.exception))
        self.assertIn("already exists", str(context.exception).lower())

    def test_module_autogenerated_name_reuses_existing(self):
        """Test that auto-generated duplicate names reuse existing module registration"""
        from solid2 import module

        # Create first module with auto-generated name
        mod1 = module(cube(5))
        first_name = mod1._module_name

        # Creating another module with the same content should work (reuses same registration)
        mod2 = module(cube(5))

        # They should have the same name
        self.assertEqual(mod1._module_name, mod2._module_name)

        # And both should work in rendering
        scene = mod1() + mod2()
        scad_output = scad_render(scene)

        # Module definition should appear only once
        self.assertEqual(scad_output.count(f"module {first_name}()"), 1)
        # But instantiation should appear twice
        self.assertEqual(scad_output.count(f"{first_name}();"), 2)


if __name__ == "__main__":
    unittest.main()
